<br>
<h4 class="add">GESTION SOUS-CATEGORIE :</h4>
<form class="form-horizontal" role="form">
    <div class="header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="false"></span></button>
    </div>
    <br>
    <div class="body">
        <div class="form-group">
            <label class="col-sm-2 control-label" for="nom">Nom</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="nom" name="nom" placeholder="Nom" required>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label" for="description"> Description</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="description" name="description" placeholder=" Description" required>
            </div>
        </div>
        
        <div class="form-group">
            <label class="col-sm-2 control-label" for="id_categorie">Catégorie</label>
            <div class="col-sm-3">
                <select class="col-sm-2 form-control">
                    <option>1</option>
                    <option>2</option>
                </select>
            </div>    
         </div>

    <div class="form-group">
        <label class="col-sm-2 control-label" for="actif">Actif</label>
            <div class="col-sm-10">
              <div class="radio">
                <label>
                  <input type="radio" name="gridActif" id="gridActif1" value="1" checked>
                 Oui
                </label>
              </div>
              <div class="radio">
                <label>
                  <input type="radio" name="gridActif" id="gridActif2" value="0">
                 Non
                </label>
              </div>
            </div>
        </div>
    </div>
    <input type="hidden" name="action" value="sous_categorie_edit">
    <div class="footer">
         <div class="user-info-box">
            <input type="submit" class="btn btn-info btn-edit" />                
        </div>
    </div>
</form>