<tbody>
<tr>
    <td><?=$sous_categorie->getId(); ?></td>
    <td><?=htmlentities($sous_categorie->getNom()); ?></td>
    <td><?=htmlentities($sous_categorie->getDescription()); ?></td>
    <td><?=$sous_categorie->getActif(); ?></td>

    <td><a href="index.php?page=admin&bloc=sous_categorie&option=edit_sous_categorie&id=<?=$sous_categorie->getId(); ?>"><img src="public/images/user_edit.png" alt="" title="" border="0" /></a></td>
    <td><a href="index.php?page=admin&bloc=sous_categorie&option=delete_sous_categorie&id=<?=$sous_categorie->getId(); ?>" class="ask"><img src="public/images/trash.png" alt="" title="" border="0" /></a></td>
</tr>
</tbody>