<tbody>
	<tr>
	    <td><?=$user->getId(); ?></td>
	    <td><?=htmlentities($user->getEmail()); ?></td>
	    <td><?=htmlentities($user->getlogin()); ?></td>
	    <td><?=$user->getActif(); ?></td>
	    <td><?=$user->getAdmin(); ?></td>

	    <td><a href="#"><img src="public/images/user_edit.png" alt="" title="" border="0" /></a></td>
	    <td><a href="#" class="ask"><img src="public/images/trash.png" alt="" title="" border="0" /></a></td>
	</tr>
</tbody>