<div>            
    <h3>Gestion des SOUS-CATEGORIES</h3>                                  
    <table id="rounded-corner">
        <thead>
        <tr>
            <th scope="col" class="rounded">Id</th>
            <th scope="col" class="rounded">Nom</th>
            <th scope="col" class="rounded">Description</th>
            <th scope="col" class="rounded">Actif</th>
            <th></th>
            <th></th>
        </tr>
        </thead>
        <?php require('apps/admin_sous_categories.php'); ?>
    </table>
    <a href="#" class="btn"><strong>Ajouter une sous-catégorie</strong></span></a>
</div>