<div>            
    <h3>Gestion des CATEGORIES</h3>                                  
    <table id="rounded-corner">
        <thead>
    	<tr>
            <th scope="col" class="rounded">Id</th>
            <th scope="col" class="rounded">Nom</th>
            <th scope="col" class="rounded">Description</th>
            <th scope="col" class="rounded">Actif</th>
            <th></th>
            <th></th>
        </tr>
        </thead>
        <?php require('apps/admin_categorie.php'); ?>
    </table>
    <br>
    <div class="user-info-box">
        <a class="btn btn-info btn-edit" href="index.php?page=admin&action=ajout_categorie" data-toggle="modal" data-target="#addCategorie">
        Ajouter une catégorie
        </a>                    
    </div>
</div>