<div>            
    <h3>Gestion des SOUS-CATEGORIES</h3>                                  
    <table id="rounded-corner">
        <thead>
        <tr>
            <th scope="col" class="rounded">Id</th>
            <th scope="col" class="rounded">Nom</th>
            <th scope="col" class="rounded">Description</th>
            <th scope="col" class="rounded">Actif</th>
            <th></th>
            <th></th>
        </tr>
        </thead>
        <?php require('apps/admin_sous_categories.php'); ?>
    </table>
    <br>
    <div class="user-info-box">
        <a class="btn btn-info btn-edit" href="index.php?page=admin&bloc=sous_categorie&option=add_sous_categorie" data-toggle="modal" data-target="#addSousCategorie">
        Ajouter une sous-catégorie
        </a>                    
    </div>
</div>
   