<br>
<h4 class="add">MODIFIER UNE CATEGORIE :</h4>
<form class="form-horizontal" role="form" method="POST">
    <div class="header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="false"></span></button>
    </div>
    <br>
    <div class="body">
        <div class="form-group">
            <label class="col-sm-2 control-label" for="nom">Nom</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="nom" name="nom" value="<?=$categorie->getNom();?>" value="" required>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label" for="description"> Description</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="description" name="description" value="<?=$categorie->getDescription();?>" required>
            </div>
        </div>
        
        <div class="form-group">
            <label class="col-sm-2 control-label" for="actif">Actif</label>
                <div class="col-sm-10">
                    <div class="radio">
                        <label>
                        <input type="radio" name="actif" id="gridActif1" value="1" <?php if ($categorie->getActif() == 1) { echo "checked";} ?>>
                        Oui
                        </label>
                    </div>
                    <div class="radio">
                        <label>
                        <input type="radio" name="actif" id="gridActif2" value="0" <?php if ($categorie->getActif() == 0) { echo "checked";} ?>>
                        Non
                        </label>
                    </div>
                </div>
        </div>
    </div>
    <input type="hidden" name="action" value="categorie_edit">
    <input type="hidden" name="id" value="<?=$categorie->getId();?>">
    <div class="footer">
         <div class="user-info-box">
            <input type="submit" class="btn btn-info btn-edit" />                
        </div>
    </div>
</form>