<form class="form-horizontal" role="form" method="POST">
    <div class="header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="false"></span></button>
    </div>
    <br>

    <div class="body">
        <div class="form-group">
            <label class="col-sm-2 control-label" for="reference">Référence</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="reference" name="reference" placeholder="Reference">
            </div>
        </div>

    <div class="body">
        <div class="form-group">
            <label class="col-sm-2 control-label" for="nom">Nom</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="nom" name="nom" placeholder="Nom" required>
            </div>
        </div>

        <div class="form-group">
            <label class="col-sm-2 control-label" for="description"> Description</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="description" name="description" placeholder=" Description" required>
            </div>
        </div>

        <div class="body">
        <div class="form-group">
            <label class="col-sm-2 control-label" for="prix">Prix</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="prix" name="prix" placeholder="prix" required>
            </div>
        </div>

        <div class="body">
        <div class="form-group">
            <label class="col-sm-2 control-label" for="tva">TVA</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="tva" name="tva" placeholder="tva" required>
            </div>
        </div>

        <div class="body">
        <div class="form-group">
            <label class="col-sm-2 control-label" for="photo">Photo</label>
            <div class="col-sm-10">
                <input type="file" class="filestyle" id="photo" name="photo" data-buttonText="Find file">
            </div>    
        </div>

        <div class="body">
        <div class="form-group">
            <label class="col-sm-2 control-label" for="poids">Poids</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="poids" name="poids" placeholder="poids" required>
            </div>
        </div>

        <div class="form-group">
            <label class="col-sm-2 control-label" for="id_categorie" id="id_categorie" name="id_categorie">Catégorie</label>
            <div class="col-sm-3">
                <select id="change_category" class="col-sm-2 form-control">
                    <?php require('apps/sous_categorie_add.php'); ?>
                </select>
                                <script>
                   $('#change_category').change(function()
                        {
                    $.get('index.php?page=admin_categorie&ajax', function(data)
                    {
                        alert(data);
                    });
                })
                </script>
            </div>    
        </div>  

        <div class="form-group">
            <label class="col-sm-2 control-label" for="id_sous_categorie" id="id_sous_categorie" name="id_sous_categorie">Sous-Catégorie</label>
            <div class="col-sm-3">
                <select id="change_sous_category" class="col-sm-2 form-control">
                    <?php require('apps/produit_add.php'); ?>
                </select>
            </div>    
         </div>

         <div class="body">
        <div class="form-group">
            <label class="col-sm-2 control-label" for="stock">Stock</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="stock" name="stock" placeholder="stock" required>
            </div>
        </div>

    <div class="form-group">
        <label class="col-xs-2 control-label" for="actif" id="actif" name="actif">Actif</label>
            <div class="col-sm-10">
              <div class="radio">
                <label>
                  <input type="radio" name="actif" id="gridActif1" value="1" checked>
                 Oui
                </label>
              </div>
              <div class="radio">
                <label>
                  <input type="radio" name="actif" id="gridActif2" value="0">
                 Non
                </label>
              </div>
            </div>
        </div>
    </div>

    <div class="footer">

        <input type="hidden" name="action" value="produit_add" />
        <div class="address new">
            <input type="submit" value="submit">
        </div>
    </div>
</form>

