<tbody>
<tr>
    <td><?=$categorie->getId()?></td>
    <td><?=htmlentities($categorie->getNom()); ?></td>
    <td><?=htmlentities($categorie->getDescription()); ?></td>
    <td><?=$categorie->getActif(); ?></td>

    <td><a href="index.php?page=admin&bloc=categorie&option=edit_categorie&id=<?=$categorie->getId(); ?>"><img src="public/images/user_edit.png" alt="" title="" border="0" /></a></td>
    <td><a href="index.php?page=admin&bloc=categorie&option=delete_categorie&id=<?=$categorie->getId(); ?>" class="ask"><img src="public/images/trash.png" alt="" title="" border="0" /></a></td>
</tr>
</tbody>