<tbody>
    <tr>
    	<td><?=$produit->getId(); ?></td>
	    <td><?=htmlentities($produit->getNom()); ?></td>
	    <td><?=htmlentities($produit->getDescription()); ?></td>
	    <td><?=$produit->getActif(); ?></td>

        <td><a href="index.php?page=admin&bloc=produit&option=edit"><img src="public/images/user_edit.png" alt="" title="" border="0" /></a></td>
    	<td><a href="index.php?page=admin&bloc=produit&option=delete_admin_produits" class="ask"><img src="public/images/trash.png" alt="" title="" border="0" /></a></td>
    </tr>
</tbody>