<tbody>
<tr>
    <td><input type="checkbox" name="" /></td>
    <td><?=$sous_categorie->getId(); ?></td>
    <td><?=htmlentities($sous_categorie->getNom()); ?></td>
    <td><?=htmlentities($sous_categorie->getDescription()); ?></td>
    <td>$<?=$sous_categorie->getActif(); ?></td>

    <td><a href="#"><img src="public/images/user_edit.png" alt="" title="" border="0" /></a></td>
    <td><a href="#" class="ask"><img src="public/images/trash.png" alt="" title="" border="0" /></a></td>
</tr>
</tbody>