<div>
    <h3>Gestion des USERS</h3>                                  
    <table id="rounded-corner">
        <thead>
        <tr>
            <th scope="col" class="rounded">Id</th>
            <th scope="col" class="rounded">Email</th>
            <th scope="col" class="rounded">Login</th>
            <th scope="col" class="rounded">Actif</th>
            <th scope="col" class="rounded">Admin</th>
            <th></th>
            <th></th>
        </tr>
        </thead>
        <?php require('apps/admin_users.php'); ?>
    </table>
    <br>
</div>