<br>
<h4 class="add">MODIFIER UN PRODUIT :</h4>

<form class="form-horizontal" role="form" method="POST">
    <div class="header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="false"></span></button>
    </div>
    <br>

    <div class="body">
        <div class="form-group">
            <label class="col-sm-2 control-label" for="reference">Référence</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="reference" name="reference" placeholder="Reference" value="<?=$produit->getReference();?>">
            </div>
        </div>

    <div class="body">
        <div class="form-group">
            <label class="col-sm-2 control-label" for="nom">Nom</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="nom" name="nom" placeholder="Nom" value="<?=$produit->getNom();?>" required>
            </div>
        </div>

        <div class="form-group">
            <label class="col-sm-2 control-label" for="description"> Description</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="description" name="description" placeholder=" Description" value="<?=$produit->getDescription();?>" required>
            </div>
        </div>

        <div class="body">
        <div class="form-group">
            <label class="col-sm-2 control-label" for="prix">Prix</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="prix" name="prix" placeholder="prix" value="<?=$produit->getPrix();?>" required>
            </div>
        </div>

        <div class="body">
        <div class="form-group">
            <label class="col-sm-2 control-label" for="tva">TVA</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="tva" name="tva" placeholder="tva" value="<?=$produit->getTva();?>" required>
            </div>
        </div>

        <div class="body">
        <div class="form-group">
            <label class="col-sm-2 control-label" for="photo">Photo</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="photo" name="photo" placeholder="photo" value="<?=$produit->getPhoto();?>">
            </div>    
        </div>

        <div class="body">
        <div class="form-group">
            <label class="col-sm-2 control-label" for="poids">Poids</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="poids" name="poids" placeholder="poids" value="<?=$produit->getPoids();?>" required>
            </div>
        </div>

        <div class="form-group">
            <label class="col-sm-2 control-label" for="id_categorie" id="id_categorie" name="id_categorie">Catégorie</label>
            <div class="col-sm-3">
                <select id="change_category" class="col-sm-2 form-control">
                    <?php require('apps/produit_add.php'); ?>
                </select>
                <script>
                   $('#change_category').change(function()
                    {
                      $.get('index.php?page=sous_categorieAjax&ajax&id='+$(this).val(), function(data)
                      {
                          $('#subcat').html(data);
                      });
                    });
                </script>
            </div>    
        </div>  
        <div id="subcat"><?php require('apps/sous_categorieAjax.php'); ?></div>
        <div class="body">
            
        <div class="form-group">
            <label class="col-sm-2 control-label" for="stock">Stock</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="stock" name="stock" placeholder="stock" required>
            </div>
        </div>

    <div class="form-group">
        <label class="col-xs-2 control-label" for="actif" id="actif" name="actif">Actif</label>
            <div class="col-sm-10">
              <div class="radio">
                <label>
                  <input type="radio" name="actif" id="gridActif1" value="1" <?php if ($produit->getActif() == 1) { echo "checked";} ?>>
                 Oui
                </label>
              </div>
              <div class="radio">
                <label>
                  <input type="radio" name="actif" id="gridActif2" value="0" <?php if ($sous_categorie->getActif() == 0) { echo "checked";} ?>>
                 Non
                </label>
              </div>
            </div>
        </div>
    </div>

    <input type="hidden" name="action" value="produit_edit">
    <input type="hidden" name="id" value="<?=$produit->getId();?>">
    <div class="footer">
         <div class="user-info-box">
            <input type="submit" class="btn btn-info btn-edit" />                
        </div>
    </div>

</form>

