<div>
    <h3>Gestion des AVIS</h3>                                  
    <table id="rounded-corner">
        <thead>
        <tr>
            <th scope="col" class="rounded">Id</th>
            <th scope="col" class="rounded">Contenu</th>
            <th scope="col" class="rounded">Note</th>
            <th scope="col" class="rounded">Date</th>
            <th scope="col" class="rounded">User</th>
            <th scope="col" class="rounded">Produit</th>
            <th></th>
        </tr>
        </thead>
        <?php require('apps/admin_avis.php'); ?>
    </table>
    <br>
</div>