<br>
<h4 class="add">MODIFIER UNE SOUS-CATEGORIE :</h4>

<form class="form-horizontal" role="form" method="POST">
    <div class="header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="false"></span></button>
    </div>
    <br>
    <div class="body">
        <div class="form-group">
            <label class="col-sm-2 control-label" for="nom">Nom</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="nom" name="nom" value="<?=htmlentities($sous_categorie->getNom())?>" required>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label" for="description"> Description</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="description" name="description" value="<?=htmlentities($sous_categorie->getDescription())?>" required>
            </div>
        </div>
        
        <div class="form-group">
            <label class="col-sm-2 control-label" for="id_categorie">Catégorie</label>
            <div class="col-sm-3">
                <select name="id_categorie" class="col-sm-2 form-control">  <?php $idCategory = $sous_categorie->getIdCategorie(); ?>
                    <?php require('apps/sous_categorie_add.php'); ?>
                </select>
            </div>    
         </div>

        <div class="form-group">
            <label class="col-sm-2 control-label" for="actif">Actif</label>
                <div class="col-sm-10">
                    <div class="radio">
                        <label>
                        <input type="radio" name="actif" id="gridActif1" value="1" <?php if ($sous_categorie->getActif() == 1) { echo "checked";} ?>>
                        Oui
                        </label>
                    </div>
                    <div class="radio">
                        <label>
                        <input type="radio" name="actif" id="gridActif2" value="0" <?php if ($sous_categorie->getActif() == 0) { echo "checked";} ?>>
                        Non
                        </label>
                    </div>
                </div>
        </div>
    </div>
    <input type="hidden" name="action" value="sous_categorie_edit">
    <input type="hidden" name="id" value="<?=$sous_categorie->getId();?>">
    <div class="footer">
         <div class="user-info-box">
            <input type="submit" class="btn btn-info btn-edit" />                
        </div>
    </div>
</form>
