	<div class="breadcrumbs">
		<div class="container">
			<div class="breadcrumbs-main">
				<ol class="breadcrumb">
					<li><a href="index.html">Home</a></li>
					<li class="active">Adresses</li>
				</ol>
			</div>
		</div>
	</div>

	<div>   
    <h3>Gestion des ADRESSES</h3>                                  
    <table id="rounded-corner">
        <thead>
        <tr>
            <th scope="col" class="rounded">Id</th>
            <th scope="col" class="rounded">Nom</th>
            <th scope="col" class="rounded">N°</th>
            <th scope="col" class="rounded">Rue</th>
			<th scope="col" class="rounded">CP</th>
			<th scope="col" class="rounded">Ville</th>
			<th scope="col" class="rounded">Pays</th>
			<th scope="col" class="rounded">Tél.</th>
			<th scope="col" class="rounded">Type</th>
			<th scope="col" class="rounded">Active</th>
            <th></th>
            <th></th>
        </tr>
        </thead>
        <?php require('apps/admin_adresse.php'); ?>
    </table>
    <br>
    <div class="user-info-box">
        <a class="btn btn-info btn-edit" href="index.php?page=admin&bloc=adresse&option=add_adresse" data-target="#addAdresse">
        Ajouter une adresse
        </a>                    
    </div>
    <br>
</div>







	<div class="account">
		<div class="container"> 
			<div class="account-bottom">
				<div class="col-md-6 account-left">
					<div class="account-top heading">
						<h3>GESTION DE VOS ADRESSES</h3>
					</div>
					<form method="POST" name="adresse" id="adresse">
					<div class="address">
						<br>						
						<input type="text" name="nom" id="nom" placeholder="Nom de votre adresse" class="form-control" >
					</div>
					<div class="address">
						<br>
						<input type="text" name="nom" id="nom" class="form-control" placeholder="Votre nom">
					</div>
					<div class="address">
						<br>
						<input name="email" type="email" class="form-control" placeholder="Votre adresse email" id="email">
					</div>
					<br>
					<div class="address">
						<span>Sexe</span>
						<label class="radio-inline">
							<input type="radio" name="sexe" id="1" value="1"> Homme
						</label>
						<label class="radio-inline">
							<input type="radio" name="sexe" id="0" value="0"> Femme
						</label>
					</div>
					<br>
					<div class="address">
						<span>Date de naissance</span>
						<input type="date" name="date_naissance">
					</div>
					<hr>
					<div class="address">
						<br>
						<input name="login" type="text" class="form-control" id="login" placeholder="Login">
					</div>
					<div class="address">
						<br>
						<input name="password1" type="password" class="form-control" id="password1" placeholder="Password">
					</div>
                    <div class="address">
						<br>
						<input name="password2" type="password" class="form-control" id="password2" placeholder="Retype password">
					</div>
					<br>
					<input type="hidden" name="action" value="create" />
					<div class="address new pull-right">
						<input type="submit" value="submit">
					</div>
					</form>
				</div>
				<div class="col-md-6 account-left">
					<form method="POST">
					<div class="account-top heading">
						<h3>CONNEXION</h3>
					</div>
					<div class="address">
						<br>
						<input name="login" type="text" class="form-control" id="login" placeholder="Login">
					</div>
					<div class="address">
						<br>
						<input name="password" type="password" class="form-control" id="password" placeholder="Password">
					</div>
					<br>
					<input type="hidden" name="action" value="login" />
					<div class="address new pull-right">
						<input type="submit" value="login">
					</div>
				</form>
				<div class="clearfix"> </div>
			</div>
		</div>
	</div>
