<tbody>
<tr>
	<td><input type="checkbox" name="" /></td>
    <td><?=$categorie->getId(); ?></td>
    <td><?=htmlentities($categorie->getNom()); ?></td>
    <td><?=htmlentities($categorie->getDescription()); ?></td>
    <td>$<?=$categorie->getActif(); ?></td>

    <td><a href="#"><img src="public/images/user_edit.png" alt="" title="" border="0" /></a></td>
    <td><a href="#" class="ask"><img src="public/images/trash.png" alt="" title="" border="0" /></a></td>
</tr>
</tbody>