<tbody>
	<tr>
	    <td><?=$avis->getId(); ?></td>
	    <td><?=htmlentities($avis->getContenu()); ?></td>
	    <td><?=$avis->getNote(); ?></td>
	    <td><?=$avis->getDate(); ?></td>
	    <td><?=$user->getLogin(); ?></td>
	    <td><?=$produit->getNom(); ?></td>

	    <td><a href="index.php?page=avis&option=update&id=<?=$avis->getId(); ?>" class="ask"><img src="public/images/trash.png" alt="" title="" border="0" /></a></td>
	</tr>
</tbody>