<form class="form-horizontal" role="form" method="POST">
    <div class="header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="false"></span></button>
    </div>
    <br>
    <div class="body">
        <div class="form-group">
            <label class="col-sm-2 control-label" for="nom">Nom</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="nom" name="nom" placeholder="Nom" required>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label" for="numero">N°</label>
            <div class="col-sm-10">
                <input type="number" class="form-control" id="numero" name="numero" placeholder="N°" required>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label" for="rue">Rue</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="rue" name="rue" placeholder="Rue" required>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label" for="numero">CP</label>
            <div class="col-sm-10">
                <input type="number" class="form-control" id="cp" name="cp" placeholder="CP" required>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label" for="ville">Ville</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="ville" name="ville" placeholder="Ville" required>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label" for="pays">Pays</label>
            <div class="col-sm-10">
                <select name="pays"> 
                    <option value="france" selected="selected">France </option>
                     <option value="allemagne">Allemagne </option>
                     <option value="luxembourg">Luxembourg </option>
                     <option value="suisse">Suisse </option>
                </select>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label" for="telephone">Téléphone</label>
            <div class="col-sm-10">
                <input type="tel" class="form-control" id="telephone" name="telephone" placeholder="Tél." required>
            </div>
        </div>
        

    </div>
    <input type="hidden" name="action" value="create">
    <div class="footer">
         <div class="user-info-box">
            <input type="submit" class="btn btn-info btn-edit" />                
        </div>
    </div>
</form>