<form class="form-horizontal" role="form" method="POST">
    <div class="header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="false"></span></button>
    </div>
    <br>
    <div class="body">
        <div class="form-group">
            <label class="col-sm-2 control-label" for="nom">Nom</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="nom" name="nom" value="<?=htmlentities($adresse->getNom())?>" required>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label" for="numero">N°</label>
            <div class="col-sm-10">
                <input type="number" class="form-control" id="numero" name="numero" value="<?=$adresse->getNumero()?>" required>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label" for="rue">Rue</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="rue" name="rue" value="<?=htmlentities($adresse->getRue())?>" required>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label" for="numero">CP</label>
            <div class="col-sm-10">
                <input type="number" class="form-control" id="cp" name="cp" value="<?=$adresse->getCp()?>" required>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label" for="ville">Ville</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="ville" name="ville" value="<?=htmlentities($adresse->getVille())?>" required>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label" for="pays">Pays</label>
            <div class="col-sm-10">
                <select name="pays" class="col-sm-2 form-control"> 
                    <option value="france" <?php if ($adresse->getPays() == "france") { echo "selected=selected"; } ?>>France </option>
                     <option value="allemagne" <?php if ($adresse->getPays() == "allemagne") { echo "selected=selected"; } ?>>Allemagne </option>
                     <option value="luxembourg" <?php if ($adresse->getPays() == "luxembourg") { echo "selected=selected"; } ?>>Luxembourg </option>
                     <option value="suisse" <?php if ($adresse->getPays() == "suisse") { echo "selected=selected"; } ?>>Suisse </option>
                </select>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label" for="telephone">Téléphone</label>
            <div class="col-sm-10">
                <input type="tel" class="form-control" id="telephone" name="telephone" value="<?=htmlentities($adresse->getTelephone())?>" required>
            </div>
        </div>
        

    </div>
    <input type="hidden" name="action" value="update">
    <input type="hidden" name="id" value="<?=$adresse->getId()?>">
    <input type="hidden" name="id_user" value="<?=$adresse->getIdUser()?>">
    <div class="footer">
         <div class="user-info-box">
            <input type="submit" class="btn btn-info btn-edit" />                
        </div>
    </div>
</form>