<tbody>
<tr>
    <td><a href="index.php?page=panier&option=finaliser&adresse=<?=$adresse->getId()?>">[ CHOISIR ]</a></td>

    <td><?=$adresse->getId(); ?></td>
    <td><?=htmlentities($adresse->getNom()); ?></td>
    <td><?=$adresse->getNumero()?></td>
    <td><?=htmlentities($adresse->getRue()); ?></td>
    <td><?=$adresse->getCp()?></td>
    <td><?=htmlentities($adresse->getVille()); ?></td>
    <td><?=htmlentities($adresse->getPays()); ?></td>
    <td><?=$adresse->getTelephone()?></td>
    <td><?=$adresse->getType()?></td>


    <td><a href="index.php?page=adresse&option=edit_adresse&id=<?=$adresse->getId(); ?>"><img src="public/images/user_edit.png" alt="" title="" border="0" /></a></td>
    <td><a href="index.php?page=adresse&option=delete_adresse&id=<?=$adresse->getId(); ?>"><img src="public/images/trash.png" alt="" title="" border="0" /></a></td>
</tr>
</tbody>