<div class="my-rating jq-stars"></div>
<form method="POST">
	<div class="form-group">
		<label for="content">Commentaire</label>
		<textarea name="content" class="form-control" id="content" placeholder="Votre commentaire"></textarea>
	</div>
	<button type="submit" class="btn btn-default">Envoyer</button>
	<!-- <input type="hidden" name="id_avis" value="<?=$avis_id?>" />
	<input type="submit" value="Ajouter"> -->
</form>

<hr>

<script>
$(function() 
{

  $(".my-rating").starRating({
  initialRating: 4,
  starSize: 25
});


});
</script>
<script src="public/js/jquery.star-rating-svg.js"></script>