<br>
<br>
<br>
<br>
<br>
<br>
<br> <!-- si alex n'est pas là, les br dansent -->
<form method="POST" action="index.php?page=avis">
		<div class="form-group">
			note
			<input type="text" id="note" name="note" /><br />
			<label for="contenu">Commentaire</label>
			<textarea name="contenu" class="form-control" id="content" placeholder="Votre commentaire"></textarea>
		</div>
		<input type="hidden" name="action" value="create">
		<input type="hidden" name="id_produit" value="<?=$produit->getId()?>">
		<button type="submit" class="btn btn-default">Envoyer</button>
	</div>
</form>

<hr>

<script>
	$(function() 
	{

	  $(".my-rating").starRating({
	  initialRating: 4,
	  starSize: 25
	});


	});
</script>
<script src="public/js/jquery.star-rating-svg.js"></script>