<div class="container row">
	<div class="col-lg-10 col-sm-10 col-xs-12">
		<div class="panel panel-default ">
			<div class="panel-heading">			
				Avis de : <span style="color: #00C8CF"><?=htmlentities($avis->getUser()->getLogin())?></span>
				| Laissé le : <span style="color: #00C8CF"><?=$avis->getDate()?></span>
				<div style="color: #00C8CF">
<?php
	require ('apps/avis_liste_etoiles.php');
?>				
				</div>		
			</div>

			<div class="panel-body">
				<p><?=htmlentities($avis->getContenu())?></p>
			</div>
		</div>
	</div>
</div>