<div class="my-rating jq-stars"></div>
<form method="POST">
	<div class="form-group">
		<label for="content">Contenu</label>
		<textarea name="content" class="form-control" id="content" placeholder="Contenu"></textarea>
	</div>
	<button type="submit" class="btn btn-default">Envoyer</button>
</form>

<script>
$(function() 
{

  $(".my-rating").starRating({
  initialRating: 4,
  starSize: 25
});


});
</script>
<script src="public/js/jquery.star-rating-svg.js"></script>