<br>
<form method="POST" action="index.php?page=avis">
		<div class="container form-group row">
			<div class="col-lg-3 col-sm-4 col-xs-5">
				<label for="note">Note</label>
				<input type="text" id="note" name="note" class="form-control" placeholder="Note de 1 à 5"/><br>
			</div>
			<div class="col-lg-12 col-sm-12 col-xs-12">
				<label for="contenu">Commentaire</label>
				<textarea name="contenu" class="form-control" id="content" placeholder="Votre commentaire"></textarea>
			</div>
		</div>
		<input type="hidden" name="action" value="create">
		<input type="hidden" name="id_produit" value="<?=$produit->getId()?>">
		<div class="container single-but">
			<button type="submit" class="btn btn-info">Envoyer</button>
		</div>
	</div>
</form>
<br>

<script>
	$(function() 
	{

	  $(".my-rating").starRating({
	  initialRating: 4,
	  starSize: 25
	});


	});
</script>
<script src="public/js/jquery.star-rating-svg.js"></script>