<br>
<div class="container">
<h4 class="add">AJOUTER UN COMMENTAIRE :</h4>
<form method="POST" action="index.php?page=avis">
	<input type="hidden" name="note" value="0">
		<div class=" form-group row">
			<div class="col-lg-3 col-sm-4 col-xs-5">	
				<div class="Clear">
				    <input class="star" type="radio" name="note" value="1"/>
				    <input class="star" type="radio" name="note" value="2"/>
				    <input class="star" type="radio" name="note" value="3" checked="checked"/>
				    <input class="star" type="radio" name="note" value="4"/>
				    <input class="star" type="radio" name="note" value="5"/>
				</div>
			</div>
			<div class="col-lg-10 col-sm-12 col-xs-12">
				<label for="contenu">Commentaire</label>
				<textarea name="contenu" class="form-control" id="content" placeholder="Votre commentaire"></textarea>
			</div>
		</div>
		<input type="hidden" name="action" value="create">
		<input type="hidden" name="id_produit" value="<?=$produit->getId()?>">
		<div class=" single-but">
			<button type="submit" class="btn btn-info">Envoyer</button>
		</div>
	</div>
</form>
<br>
</div>