<div class="breadcrumbs">
	<div class="container">
		<div class="breadcrumbs-main">
			<ol class="breadcrumb">
				<li><a href="index.php?page=home">Home</a></li>
				<li class="active"><?=htmlentities($categorie->getNom())?></li>
			</ol>
		</div>
	</div>
</div>

<div class="bikes">
	<div class="product-one">	
		<?php require('apps/categorie_produits.php'); ?>
		<br>
		<div class="clearfix"></div>
	</div>
</div>