<div class="breadcrumbs">
	<div class="container">
		<div class="breadcrumbs-main">
			<ol class="breadcrumb">
				<li><a href="index.html">Home</a></li>
				<li class="active">Contactez-nous</li>
			</ol>
		</div>
	</div>
</div>

<div class="contact">
	<div class="container">
		<div class="contact-top heading"> 
			<h3>CONTACTEZ NOUS</h3>
		</div>
		<div class="contact-bottom"> 
			Votre message a bien été envoyé, merci !  :)
			<div class="clearfix"> </div>
		</div>
	</div>
</div>

<div class="map">
	<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1319.647484599286!2d7.739824843542966!3d48.58505076589609!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4796c8495cd6c45f%3A0x4a79d7f5edad6def!2s6+Rue+du+Faubourg+de+Saverne%2C+67000+Strasbourg!5e0!3m2!1sfr!2sfr!4v1464781648698" frameborder="0" style="border:0"></iframe>
</div>