<div class="breadcrumbs">
	<div class="container">
		<div class="breadcrumbs-main">
			<ol class="breadcrumb">
				<li><a href="index.php?page=home">Home</a></li>
				<li class="active">Message envoyé !</li>
			</ol>
		</div>
	</div>
</div>

<div>
	<br>  
    <h3 class="merci">Message envoyé !</h3>
    <div class="fin">
    	<div>Merci pour votre message, il sera traité au plus vite.</div>
    	<br>
		<a href="index.php?page=home"><button class="btn btn-info">Retour à l'accueil</button></a>
	</div>
</div>
