<li class="grid"><a href="#"><?=$categorie->getNom();?></a>
	<div class="mepanel">
		<div class="row">
			<div class="col1 me-one">
				<h4>Shop</h4>
				<ul>
					<li><a href="index.php?page=categorie">Nouveautés</a></li>
					<li><a href="index.php?page=categorie">Promotions</a></li>
				</ul>
			</div>
			<div class="col1 me-one">
				<h4>Vélos</h4>
				<ul>
					<li><a href="index.php?page=categorie"></a></li>
					<li><a href="index.php?page=categorie">Vélos de course</a></li>
					<li><a href="index.php?page=categorie">VTT</a></li>
				</ul>
			</div>
		</div>
	</div>
</li>