<div class="top-header">
	<div class="container">
		<div class="top-header-main">
			<div class="col-md-6 top-header-left">
				<a href="index.php?page=home"><img src="public/images/logo.jpg" alt="" /></a>
			</div>
			<div class="col-md-6 top-header-right">
				<div class="cart box_1">
					<h3><a href="index.php?page=user">Mon compte</a></h3>
					<br>
					<a href="index.php?page=panier">
						<div class="total">
							<span class="simpleCart_total"></span> (<span id="simpleCart_quantity" class="simpleCart_quantity"></span> items)
						</div>
						<img src="public/images/cart-1.png" alt="" />
					</a>
					<p><a href="javascript:;" class="simpleCart_empty">Vider le panier</a></p>
					<div class="clearfix"> </div>
				</div>
			</div>
			<div class="clearfix"></div>
		</div>
	</div>
</div>
	<div class="header-bottom">
		<div class="container">
			<div class="top-nav">
				<ul class="memenu skyblue bandeau-nav">
					<li class="active"><a href="index.php?page=home">Home</a></li>
					<li class="grid"><a href="#">Femme</a>
						<div class="mepanel">
							<div class="row">
								<div class="col1 me-one">
									<h4>Shop</h4>
									<ul>
										<li><a href="index.php?page=categorie">Nouveautés</a></li>
										<li><a href="index.php?page=categorie">Promotions</a></li>
									</ul>
								</div>
								<div class="col1 me-one">
									<h4>Bikes</h4>
									<ul>
										<li><a href="index.php?page=categorie">Vélos de ville</a></li>
										<li><a href="index.php?page=categorie">Vélos de course</a></li>
										<li><a href="index.php?page=categorie">VTT</a></li>
									</ul>	
								</div>
							</div>
						</div>
					</li>
					<li class="grid"><a href="#">Homme</a>
						<div class="mepanel">
							<div class="row">
								<div class="col1 me-one">
									<h4>Shop</h4>
									<ul>
										<li><a href="index.php?page=categorie">Nouveautés</a></li>
										<li><a href="index.php?page=categorie">Promotions</a></li>
									</ul>
								</div>
								<div class="col1 me-one">
									<h4>Bikes</h4>
									<ul>
										<li><a href="index.php?page=categorie">Vélos de ville</a></li>
										<li><a href="index.php?page=categorie">Vélos de course</a></li>
										<li><a href="index.php?page=categorie">VTT</a></li>
									</ul>	
								</div>
							</div>
						</div>
					</li>
					<li class="grid"><a href="#">Enfant</a>
						<div class="mepanel">
							<div class="row">
								<div class="col1 me-one">
									<h4>Shop</h4>
									<ul>
										<li><a href="index.php?page=categorie">Nouveautés</a></li>
										<li><a href="index.php?page=categorie">Promotions</a></li>
									</ul>
								</div>
								<div class="col1 me-one">
									<h4>Bikes</h4>
									<ul>
										<li><a href="index.php?page=categorie">Vélos de ville</a></li>
										<li><a href="index.php?page=categorie">Vélos de course</a></li>
										<li><a href="index.php?page=categorie">VTT</a></li>
									</ul>	
								</div>
							</div>
						</div>
					</li>
					<li class="grid"><a href="#">VTT</a>
						<div class="mepanel">
							<div class="row">
								<div class="col1 me-one">
									<h4>Shop</h4>
									<ul>
										<li><a href="index.php?page=categorie">Nouveautés</a></li>
										<li><a href="index.php?page=categorie">Promotions</a></li>
									</ul>
								</div>
								<div class="col1 me-one">
									<h4>Genre</h4>
									<ul>
										<li><a href="index.php?page=categorie">Homme</a></li>
										<li><a href="index.php?page=categorie">Femme</a></li>
										<li><a href="index.php?page=categorie">Enfant</a></li>
									</ul>	
								</div>
							</div>
						</div>
					</li>
					<li class="grid"><a href="#">Course</a>
						<div class="mepanel">
							<div class="row">
								<div class="col1 me-one">
									<h4>Shop</h4>
									<ul>
										<li><a href="index.php?page=categorie">Nouveautés</a></li>
										<li><a href="index.php?page=categorie">Promotions</a></li>
									</ul>
								</div>
								<div class="col1 me-one">
									<h4>Genre</h4>
									<ul>
										<li><a href="index.php?page=categorie">Homme</a></li>
										<li><a href="index.php?page=categorie">Femme</a></li>
										<li><a href="index.php?page=categorie">Enfant</a></li>
									</ul>	
								</div>
							</div>
						</div>
					</li>
					<li class="grid"><a href="#">Ville</a>
						<div class="mepanel">
							<div class="row">
								<div class="col1 me-one">
									<h4>Shop</h4>
									<ul>
										<li><a href="index.php?page=categorie">Nouveautés</a></li>
										<li><a href="index.php?page=categorie">Promotions</a></li>
									</ul>
								</div>
								<div class="col1 me-one">
									<h4>Genre</h4>
									<ul>
										<li><a href="index.php?page=categorie">Homme</a></li>
										<li><a href="index.php?page=categorie">Femme</a></li>
										<li><a href="index.php?page=categorie">Enfant</a></li>
									</ul>
								</div>
							</div>
						</div>
					</li>
				</ul>
			</div>
			<div class="clearfix"> </div>
		</div>
	</div>