<div class="top-header">
	<div class="container">
		<div class="top-header-main">
			<div class="col-md-6 top-header-left">
				<a href="index.php?page=home"><img src="public/images/logo.jpg" alt="" /></a>
			</div>
			<div class="col-md-6 top-header-right">
				<div class="cart box_1">
					<h3><a href="index.php?page=user">Mon compte</a></h3>
					<h3><a href="index.php?page=user&action=logout">Logout</a></h3>
					<br>
					<a href="index.php?page=panier">
						<div class="total">
							<span class="simpleCart_total"></span> (<span id="simpleCart_quantity" class="simpleCart_quantity"></span> items)
						</div>
						<img src="public/images/cart-1.png" alt="" />
					</a>
					
					<div class="clearfix"> </div>
				</div>
			</div>
			<div class="clearfix"></div>
		</div>
	</div>
</div>
	<div class="header-bottom">
		<div class="container">
			<div class="top-nav">
				<ul class="memenu skyblue bandeau-nav">
					<li><a href="index.php?page=home">Home</a></li>
				<?php require('apps/header_menu_categorie.php'); ?>
			<div class="clearfix"> </div>
		</div>
	</div>