<div class="col-md-3 product-left">
	<div class="p-one simpleCart_shelfItem">
		<a href="index.php?page=produit&id=<?=$produit->getId();?>">
			<img src="public/images/<?=$produit->getPhoto();?>" alt="" />
			<div class="mask">
				<span>Quick View</span>
			</div>
		</a>
		<h4><a href="index.php?page=produit&id=<?=$produit->getId();?>"><?=$produit->getNom();?></a></h4>
		<p><a href="index.php?page=produit&id=<?=$produit->getId();?>"> <span class=" item_price"><?=$produit->getPrix();?> €</span></a></p>
	</div>
</div>
