	<br>
	<div class="banner">
		<img src="public/images/banner-1.jpg" alt="super banner">
	</div>
	<div class="breadcrumbs">
		<div class="container">
			<div class="breadcrumbs-main">
				<ol class="breadcrumb">
					<li><a href="index.php?page=home">Home</a></li>
				</ol>
			</div>
		</div>
	</div>
	
	<div class="bikes"> 
		<div class="product-one">
			<?php require('apps/home_fiche_produit.php'); ?>
			<br>
			<div class="clearfix"></div>
		</div>
	</div>