	<div class="breadcrumbs">
		<div class="container">
			<div class="breadcrumbs-main">
				<ol class="breadcrumb">
					<li><a href="index.html">Home</a></li>
					<li class="active">Mon Panier</li>
				</ol>
			</div>
		</div>
	</div>

	<div class="ckeckout">
		<div class="container">
			<div class="ckeckout-top">
			<div class=" cart-items heading">
				<h3>Mon panier (Qté)</h3>
				<br>
			<table id="rounded-corner" >
				<thead>
				<tr class="unit">
					<th scope="col" class="rounded"><span>Item</span></th>
					<th class="rounded"><span>Produit</span></th>
					<th class="rounded"><span>Qté</span></th>
					<th class="rounded"><span>Prix Unit TTC</span></th>
					<th class="rounded"><span>TOTAL Poids</span></th>
					<th class="rounded"><span>TOTAL Prix TTC</span></th>
					<th class="rounded">EDIT</th>
					<th class="rounded">SUPPR</th>
				</tr>
				</thead>
				<tbody>
				<tr class="cart-header">
					<td class="ring-in rounded"><a href="" ><img src="public/images/velo.jpg" class="img-responsive" alt="Photo du produit"></a></td>
					<td class="rounded"><span>$id</span></td>
					<td class="rounded"><span>$nbr_produit</span></td>
					<td class="rounded"><span>$prix</span></td>
					<td class="rounded"><span>$poidsX$nbr</span></td>
					<td class="rounded"><span>$prixX$nbr</span></td>
					<td><a href=""><img src="public/images/user_edit.png" alt="" title="" border="0" /></a></td>
    				<td><a href="" class="ask"><img src="public/images/trash.png" alt="" title="" border="0" /></a></td>
				</tr>
				</tbody>
			</table>
				<h4>Nombre de vélos : <?=$nombre_produits?></h4>
				<h4>Poids total : <?=$poids?></h4>
				<h4>Prix total : <?=$prix?> Euros</h4>
				
			</div>  
			</div>
		</div>
	</div>