<tr class="cart-header">
	<td class="ring-in rounded"><a href="" ><img src="<?=htmlentities($produit->getPhoto())?>" class="img-responsive" alt="Photo du produit"></a></td>
	<td class="rounded"><span><?=htmlentities($produit->getNom())?></span></td>
	<td class="rounded"><span><?=$quantite?></span></td>
	<td class="rounded"><span><?=$produit->getPrix()?> €</span></td>
	<td class="rounded"><span><?=$prixTotal?> €</span></td>
	<td class="rounded"><span><?=htmlentities($produit->getDescription())?></span></td>

	<td>
		<form method="POST">
			<input type="hidden" name="id_produit" value="<?=$produit->getId()?>">
			<input type="hidden" name="quantite" value="1">
			<input type="hidden" name="action" value="delete_produit">
			<input type="submit" class="btn btn-warning" value="Enlever 1 vélo">
		</form>
	</td>
</tr>