<div class="flex">
	<div class="flex-item">
		<h3 class="adresses">Adresse de livraison :</h3>
			<div><?=$user->getPrenom()?> <?=$user->getNom()?></div>
			<div><?=$adresse->getNumero()?> <?=$adresse->getRue()?></div> 
			<div><?=$adresse->getCp()?> <?=$adresse->getVille()?></div>
			<div><?=$adresse->getPays()?></div>
	</div>
	
	<div class="flex-item">
		<h3 class="adresses">Payer par CB :</h3>
    	<img src="public/images/cb.jpg" alt="">
	</div>
</div>

<div>


		<form method="POST">
			<input type="hidden" name="adresse" value="<?=$adresse->getId()?>">	
			<input type="hidden" name="action" value="paiementok"><input type="hidden" name="adresse" value="<?=$adresse->getId()?>">	
		<input type="submit" class="btn btn-info btn-panier pull-right" value="FINALISER LA COMMANDE">
	</form>

	
</div>
