<div class="breadcrumbs">
	<div class="container">
		<div class="breadcrumbs-main">
			<ol class="breadcrumb">
				<li><a href="index.php?page=home">Home</a></li>
				<li class="active">Mon Panier</li>
			</ol>
		</div>
	</div>
</div>

<div>
	<br> 
    <div class="fin">
    	<div>Votre panier est vide :(</div>
    	<br>
		<a href="index.php?page=home"><button class="btn btn-info">Par ici les commandes :)</button></a>
	</div>
</div>
