<div class="flex">
	<div class="flex1">
		<h3 class="adresses">Adresse de livraison :</h3>
			<div><strong>Nom : </strong>$nom</div>
			<div><strong>Numéro de rue : </strong>$numero</div>
			<div><strong>Rue : </strong>$rue</div>
			<div><strong>CP : </strong>$cp</div>
			<div><strong>Ville : </strong>$ville</div>
			<div><strong>Pays : </strong>$pays</div>
			<div><strong>Tél. : </strong>$telephone</div>
	</div>
	<div class="flex2">
		<h3 class="adresses">Adresse de facturation :</h3>
			<div><strong>Nom : </strong>$nom</div>
			<div><strong>Numéro de rue : </strong>$numero</div>
			<div><strong>Rue : </strong>$rue</div>
			<div><strong>CP : </strong>$cp</div>
			<div><strong>Ville : </strong>$ville</div>
			<div><strong>Pays : </strong>$pays</div>
			<div><strong>Tél. : </strong>$telephone</div>
	</div>
</div>
<div class="btn-panier">
	<a href="index.php?page=adresse">
		<button type="button" class="btn btn-info">VALIDER LA COMMANDE</button>
	</a>
</div>