	<div class="breadcrumbs">
		<div class="container">
			<div class="breadcrumbs-main">
				<ol class="breadcrumb">
					<li><a href="index.html">Home</a></li>
					<li class="active">Mon Panier</li>
				</ol>
			</div>
		</div>
	</div>
	<div class="ckeckout">
		<div class="container">
			<div class="ckeckout-top">
			<div class=" cart-items heading">
				<h3>Mon panier (Qté)</h3>
				<script>$(document).ready(function(c) {
					$('.close1').on('click', function(c){
						$('.cart-header').fadeOut('slow', function(c){
							$('.cart-header').remove();
						});
						});	  
					});
				</script>
				<script>$(document).ready(function(c) {
					$('.close2').on('click', function(c){
						$('.cart-header1').fadeOut('slow', function(c){
							$('.cart-header1').remove();
						});
						});	  
					});
				</script>
				<script>$(document).ready(function(c) {
					$('.close3').on('click', function(c){
						$('.cart-header2').fadeOut('slow', function(c){
							$('.cart-header2').remove();
						});
						});	  
					});
				</script>
				
			<div class="in-check" >
				<ul class="unit">
					<li class="tab1"><span>Item</span></li>
					<li class="tab2"><span>Nom du Produit</span></li>		
					<li class="tab3"><span>Prix Unitaire (TTC)</span></li>
					<li class="tab4"><span>Qté</span></li>
					<li class="tab5"> </li>
					<div class="clearfix"> </div>
				</ul>
				<ul class="cart-header">
					<li class="ring-in tab1"><a href="" ><img src="public/images/velo.jpg" class="img-responsive" alt="Photo du produit"></a>
					</li>
					<li class="tab2"><span>Nom du produit</span></li>
					<li class="tab3"><span>Prix unitaire TTC</span></li>
					<li class="tab4"><span>Qté en panier</span></li>
					<li class="tab5"> <a href="" class="add-cart cart-check">MODIFIER</a></li>
				<div class="clearfix"> </div>
				</ul>
			</div>
			
			</div>  
			</div>
		</div>
	</div>