<div class="quantity_box">
	<ul class="product-qty">
		<span>Quantité :</span>
		<select name="quantite">
			<?php
			if ($produit->getStock() != 0)
				require('apps/produit_quantite.php');
			else
				echo "<option>plus de stock</option>";
			?>
		</select>
	</ul>
</div>

<div class="clearfix"></div>

<div class="single-but">
	<input type="hidden" name="id_produit" value="<?=$produit->getId(); ?>">
	<input type="hidden" name="action" value="ajout_panier">
	<?php 
	if ($produit->getStock() != 0)
		{
			echo "<input type=\"submit\" value=\"ajouter\"/>";
		}
		else
			echo "plus en stock, désolé";
		?>
</form>