	<form method="POST" action="index.php?page=panier">
	<div class="breadcrumbs">
		<div class="container">
			<div class="breadcrumbs-main">
				<ol class="breadcrumb">
					<li><a href="index.php?page=home">Home</a></li>
					<li><a href="index.php?page=categorie&id=<?=$produit->getCategorie()->getId()?>"><?=$produit->getCategorie()->getNom()?></a></li>
					<li><a href="index.php?page=sous_categorie&id=<?=$produit->getSousCategorie()->getId()?>"><?=$produit->getSousCategorie()->getNom()?></a></li>
					<li class="active"><?=htmlentities($produit->getNom()); ?></li>
				</ol>
			</div>
		</div>
	</div>
	<br>
	<div class="container">
		<div class="row">
			<div class="col-md-5 single-top-left img-product">	
				<a href=""><img src="<?=$produit->getPhoto();?>" /></a>
			</div>
			<div class="col-md-7 single-top-right">
				<div class="details-left-info simpleCart_shelfItem">
					<h3><?=htmlentities($produit->getNom()); ?></h3>
					<p class="availability">Disponibilité : <span class="color"><?=$produit->getStock()?> vélo(s) en stock</span></p>
					<div class="price_single">
						<span class="actual item_price"><?=$produit->getPrix(); ?> €</span>
					</div>
					<h2 class="quick">Description :</h2>
					<p class="quick_desc"> <?=htmlentities($produit->getDescription()); ?></p>

					<h2 class="quick">Poids :</h2>
					<p class="quick_desc"> <?=$produit->getPoids(); ?> Kg</p>

					<?php require('apps/produit_by_profile.php'); ?>

					</div>
				</div>
			</div>
			<div class="clearfix"></div>
		</div>
		<div class="clearfix"> </div>
	</div>
	<br />