	<form method="POST" action="index.php?page=panier">
	<div class="breadcrumbs">
		<div class="container">
			<div class="breadcrumbs-main">
				<ol class="breadcrumb">
					<li><a href="index.php?page=home">Home</a></li>
					<li class="active"><?=htmlentities($produit->getNom()); ?></li>
				</ol>
			</div>
		</div>
	</div>
	<br>
	<div class="container">
		<div class="row">
			<div class="col-md-5 single-top-left img-product">	
				<a href=""><img src="public/images/<?=$produit->getPhoto(); ?>" /></a>
			</div>
			<div class="col-md-7 single-top-right">
				<div class="details-left-info simpleCart_shelfItem">
					<h3><?=htmlentities($produit->getNom()); ?></h3>
					<p class="availability">Disponibilité : <span class="color"><?=$produit->getStock()?> vélo(s) en stock</span></p>
					<div class="price_single">
						<span class="actual item_price"><?=$produit->getPrix(); ?> €</span>
					</div>
					<h2 class="quick">Description :</h2>
					<p class="quick_desc"> <?=htmlentities($produit->getDescription()); ?></p>
					<div class="quantity_box">
						<ul class="product-qty">
							<span>Quantité :</span>
							<select name="quantite">
								

					<?php
					if ($produit->getStock() != 0)
						require('apps/produit_quantite.php'); 
					else
						echo "<option>plus de stock</option>";
					 
					 ?>



							</select>
						</ul>
					</div>
					<div class="clearfix"></div>
					<div class="single-but">
						<input type="hidden" name="id_produit" value="<?=$produit->getId(); ?>">
							<input type="hidden" name="action" value="ajout_panier">
							<?php if ($produit->getStock() != 0) 
							{
								echo "<input type=\"submit\" value=\"ajouter\"/>";
							}
							else
								echo "plus en stock, désolé";
							?>
						
					</form>
					</div>
				</div>
			</div>
			<div class="clearfix"></div>
		</div>
		<div class="clearfix"> </div>
	</div>
	<br />