	<div class="breadcrumbs">
		<div class="container">
			<div class="breadcrumbs-main">
				<ol class="breadcrumb">
					<li><a href="index.html">Home</a></li>
					<li class="active">NOM DU PRODUIT</li>
				</ol>
			</div>
		</div>
	</div>
	<br>
	<div class="container">
		<div class="row">
			<div class="col-md-5 single-top-left img-product">	
				<a href=""><img src="public/images/velo.jpg" /></a>
			</div>
			<div class="col-md-7 single-top-right">
				<div class="details-left-info simpleCart_shelfItem">
					<h3>Nom du produit</h3>
					<p class="availability">Disponibilité : <span class="color">In stock</span></p>
					<div class="price_single">
						<span class="actual item_price">xxx €</span>
					</div>
					<h2 class="quick">Description :</h2>
					<p class="quick_desc"> Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim placerat facer possim assum. Typi non habent claritatem insitam; es</p>
					<div class="quantity_box">
						<ul class="product-qty">
							<span>Quantité :</span>
							<select>
								<option>1</option>
								<option>2</option>
								<option>3</option>
								<option>4</option>
								<option>5</option>
								<option>6</option>
							</select>
						</ul>
					</div>
					<div class="clearfix"></div>
					<div class="single-but item_add">
						<input type="submit" value="ajouter"/>
					</div>
				</div>
			</div>
			<div class="clearfix"></div>
		</div>
		<div class="clearfix"> </div>
	</div>
	<br>