<form class="form-horizontal" role="form" method="POST">

    <div class="header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="false"></span></button>
    </div>
    <br>
    <div class="body">
        <div class="form-group">
            <label class="col-sm-2 control-label" for="login">Login</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="login" name="login" placeholder="login" required checkbox disabled>
            </div>
        </div>

    <div class="body">
        <div class="form-group">
            <label class="col-sm-2 control-label" for="email">Email</label>
            <div class="col-sm-10">
                <input type="email" class="form-control" id="email" name="email" placeholder="votre@email.com">
            </div>
        </div>


        <div class="form-group">
            <label class="col-sm-2 control-label" for="password1"> Votre mot de passe</label>
            <div class="col-sm-10">
                <input type="password" class="form-control" id="password1" name="password1" placeholder="mot de passe" required>
            </div>
        </div>

        <div class="form-group">
            <label class="col-sm-2 control-label" for="password2"> Mot de passe à nouveau</label>
            <div class="col-sm-10">
                <input type="password" class="form-control" id="password2" name="password2" placeholder="mot de passe à nouveau" required>
            </div>
        </div>


    <div class="form-group">
        <label class="col-xs-2 control-label" for="actif" id="actif" name="actif">Désactiver son compte</label>
            <div class="col-sm-10">
              <div class="radio">
                <label>
                  <input type="radio" name="actif" id="gridActif1" value="1">
                 Oui
                </label>
              </div>
              <div class="radio">
                <label>
                  <input type="radio" name="actif" id="gridActif2" value="0" checked>
                 Non
                </label>
              </div>
            </div>
        </div>
    </div>

	<div>   
    <h3>Votre adresse</h3>                                  
    <table id="rounded-corner">
        <thead>
        <tr>
            <th scope="col" class="rounded"></th>
            <th scope="col" class="rounded">Id</th>
            <th scope="col" class="rounded">Nom</th>
            <th scope="col" class="rounded">N°</th>
            <th scope="col" class="rounded">Rue</th>
			<th scope="col" class="rounded">CP</th>
			<th scope="col" class="rounded">Ville</th>
			<th scope="col" class="rounded">Pays</th>
			<th scope="col" class="rounded">Tél.</th>
			<th scope="col" class="rounded">Type</th>
            <th></th>
            <th></th>
        </tr>
        </thead>
        <?php require('apps/adresse_liste.php'); ?>
    </table>
    <br>
    <div class="user-info-box">
        <a class="btn btn-info btn-edit" href="index.php?page=adresse&option=add_adresse" data-target="#addAdresse">
        Ajouter une adresse
        </a>                    
    </div>
    <br>
</div>
    <div class="footer">

        <input type="hidden" name="action" value="produit_add" />
        <div class="address new">
            <input type="submit" value="submit">
        </div>
    </div>
</form>

