    <div class="breadcrumbs">
        <div class="container">
            <div class="breadcrumbs-main">
                <ol class="breadcrumb">
                    <li><a href="index.html">Home</a></li>
                    <li class="active">Mon profil</li>
                </ol>
            </div>
        </div>
    </div>

<form class="form-horizontal" role="form" method="POST" action="index.php?page=user">

    <div class="header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="false"></span></button>
    </div>
    <br>
    <div class="body">
        <div class="form-group">
            <label class="col-sm-2 control-label" for="login">Login (obligatoire)</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="login" name="login" value="<?=$user->getLogin();?>">
            </div>
        </div>

    <div class="body">
    <div class="form-group">
        <label class="col-sm-2 control-label" for="email">Email (obligatoire)</label>
        <div class="col-sm-10">
            <input type="email" class="form-control" id="email" name="email" value="<?=$user->getEmail();?>">
        </div>
    </div>

        <div class="form-group">
        <label class="col-sm-2 control-label" for="password1"> Votre mot de passe actuel (obligatoire)</label>
        <div class="col-sm-10">
            <input type="password" class="form-control" id="password1" name="password1" placeholder="Mot de passe actuel" required>
        </div>
    </div>

    <div class="form-group">
        <label class="col-sm-2 control-label" for="password2">Votre nouveau mot de passe</label>
        <div class="col-sm-10">
            <input type="password" class="form-control" id="password2" name="password2" placeholder="Votre nouveau mot de passe">
        </div>
    </div>

    <div class="form-group">
        <label class="col-sm-2 control-label" for="password3">Votre nouveau mot de passe</label>
        <div class="col-sm-10">
            <input type="password" class="form-control" id="password3" name="password3" placeholder="Votre nouveau mot de passe">
        </div>
    </div>
    </div>
        


    <div class="form-group">
        <label class="col-xs-2 control-label" for="actif" id="actif" name="actif">Désactiver son compte</label>
            <div class="col-sm-10">
              <div class="radio">
                <label>
                  <input type="radio" name="actif" id="gridActif1" value="0">
                 Oui
                </label>
              </div>
              <div class="radio">
                <label>
                  <input type="radio" name="actif" id="gridActif2" value="1" checked>
                 Non
                </label>
              </div>
            </div>
        </div>
    </div>
</div>
</div>

    <div class="footer">
        <div class="address new">
            <input type="hidden" name="id" value="<?=$user->getId(); ?>">
            <input type="hidden" name="action" value="update_user">
            <input type="submit" value="valider">
        
        </div>
    </div>
</form>