	<div class="breadcrumbs">
		<div class="container">
			<div class="breadcrumbs-main">
				<ol class="breadcrumb">
					<li><a href="index.php?page=home">Home</a></li>
					<li><a href=""><?=htmlentities($categorie->getNom())?></a></li>
					<li class="active"><?=$sous_categorie->getNom()?></li>
				</ol>
			</div>
		</div>
	</div>
	<div class="product">
		<div class="container">
			<div class="product-main">
				<div class="col-md-9 p-left">
				<div class="product-one">
				
				<?php require('apps/sous_categorie_produits.php'); ?>
				
				<div class="clearfix"> </div>
			</div>
			</div>
			
			
		</div>
	</div>
	</div>
	<!--end-product-->
