<div class="col-md-4 product-left single-left">
	<div class="p-one simpleCart_shelfItem">
		<a href="index.php?page=produit&id=<?=$produit->getId()?>">
			<img src="<?=$produit->getPhoto()?>" alt="" />
			<div class="mask mask1">
				<span>Détails</span>
			</div>
		</a>
		<h4><?=$produit->getNom()?></h4>
		<p><a class="item_add" href="index.php?page=produit&id=<?=$produit->getId()?>"><i></i> 
			<span class=" item_price"><?=$produit->getPrix()?> €</span>
		</a></p>
	</div>
</div>