	<div class="breadcrumbs">
		<div class="container">
			<div class="breadcrumbs-main">
				<ol class="breadcrumb">
					<li><a href="index.php?page=home">Home</a></li>
					<li><a href="index.php?page=categorie&id=<?=$categorie->getId();?>"><?=htmlentities($categorie->getNom())?></a></li>
					<li class="active"><?=$sous_categorie->getNom()?></li>
				</ol>
			</div>
		</div>
	</div>
	<div class="bikes">
		<div class="product-one">	
			<?php require('apps/sous_categorie_produits.php'); ?>
			<br>
			<div class="clearfix"></div>
		</div>
	</div>

